CameraBazaar.Web/Models/Cameras/AddCameraViewModel.cs
namespace CameraBazaar.Web.Models.Cameras
{
    using Data.Models;
    using Infrastructure.Validations;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class AddCameraViewModel
    {
        public CameraMakeType Make { get; set; }

        [Required]
        [MaxLength(100)]
        [Model]
        public string Model { get; set; }

        public decimal Price { get; set; }

        [Range(0, 100)]
        public int Quantity { get; set; }

        [Display(Name = "Min Shutter Speed")]
        [Range(1, 30)]
        public int MinShutterSpeed { get; set; }

        [Display(Name = "Max Shutter Speed")]
        [Range(2000, 8000)]
        public int MaxShutterSpeed { get; set; }

        [Display(Name = "Min ISO")]
        public MinISOType MinISO { get; set; }

        [Display(Name = "Max ISO")]
        [Range(200, 409600)]
        [MaxISO]
        public int MaxISO { get; set; }

        [Display(Name = "Full Frame")]
        public bool IsFullFrame { get; set; }

        [Display(Name = "Video Resolution")]
        [Required]
        [StringLength(15)]
        public string VideoResolution { get; set; }

        [Display(Name = "Light Metering")]
        public IEnumerable<LightMeteringType> LightMeterings { get; set; }

        [Required]
        [StringLength(6000)]
        public string Description { get; set; }

        [Display(Name = "Image URL")]
        [Required]
        [StringLength(2000, MinimumLength = 10)]
        [ImageURL]
        public string ImageURL { get; set; }
    }
}

CameraBazaar.Web/Controllers/CamerasController.cs
namespace CameraBazaar.Web.Controllers
{
    using CameraBazaar.Services.Models;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.Cameras;
    using Services.Contracts;

    public class CamerasController : BaseController
    {
        private readonly ICameraService cameraService;
        private readonly UserManager<User> userManager;

        public CamerasController(
            UserManager<User> userManager,
            ICameraService cameraService)
        {
            this.userManager = userManager;
            this.cameraService = cameraService;
        }

        public IActionResult All()
        {
            var cameras = this.cameraService.AllCameras();
            return this.View(cameras);
        }

        [Authorize]
        public IActionResult Add() => this.View();

        [Authorize]
        [HttpPost]
        public IActionResult Add(AddCameraViewModel cameraModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(cameraModel);
            }

            if (cameraModel.LightMeterings == null)
            {
                ModelState.AddModelError(nameof(cameraModel.LightMeterings), "Light Metering must have a value!");
                return this.View(cameraModel);
            }

            this.cameraService.Create(cameraModel.Make, cameraModel.Model, cameraModel.Price, cameraModel.Quantity,
                cameraModel.MinShutterSpeed, cameraModel.MaxShutterSpeed, cameraModel.MinISO, cameraModel.MaxISO,
                cameraModel.IsFullFrame, cameraModel.VideoResolution, cameraModel.LightMeterings, cameraModel.Description,
                cameraModel.ImageURL, this.userManager.GetUserId(User));

            return this.RedirectToAll(); ;
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.userManager.GetUserId(User);

            var exist = this.cameraService.Exist(id, userId);

            if (!exist)
            {
                this.SetError("You can not edit This camera!");
                return this.RedirectToAll();
            }

            var camModel = this.cameraService.FindToEdit(id);

            if (camModel == null)
            {
                this.SetError("The camera you want to edit does not exist!");
                return this.RedirectToAll();
            }
            
            return this.View(camModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, EditCameraServiceModel cameraModel)
        {
            var userId = this.userManager.GetUserId(User);

            var exist = this.cameraService.Exist(id, userId);

            if (!exist)
            {
                this.SetError("You can not edit This camera!");
                return this.RedirectToAll();
            }

            if (!ModelState.IsValid)
            {
                return this.View(cameraModel);
            }

            var success = this.cameraService.Edit(id, cameraModel.Make, cameraModel.Model, cameraModel.Price, cameraModel.Quantity,
                cameraModel.MinShutterSpeed, cameraModel.MaxShutterSpeed, cameraModel.MinISO, cameraModel.MaxISO,
                cameraModel.IsFullFrame, cameraModel.VideoResolution, cameraModel.LightMeterings, cameraModel.Description,
                cameraModel.ImageURL);

            if (!success)
            {
                this.SetError("The camera you want to edit does not exist!");
                return this.RedirectToAll();
            }
            
            return RedirectToAction(nameof(UsersController.Profile), new { Username = this.User.Identity.Name });
        }

        public IActionResult Details(int id)
        {
            var camera = this.cameraService.Details(id);

            if (camera == null)
            {
                this.SetError("The camera does not exist!");
                return this.RedirectToAll();
            }

            return this.View(camera);
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            var userId = this.userManager.GetUserId(User);

            var exist = this.cameraService.Exist(id, userId);

            if (!exist)
            {
                this.SetError("The camera you want to delete does no exist!");
                return this.RedirectToAll();
            }

            return this.View(id);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Destroy(int id)
        {
            var userId = this.userManager.GetUserId(User);

            var exist = this.cameraService.Exist(id, userId);

            if (!exist)
            {
                this.SetError("The camera you want to delete does no exist!");
                return this.RedirectToAll();
            }

            var success = this.cameraService.Delete(id);

            if (!success)
            {
                this.SetError("The camera you want to delete does no exist!");
            }

            return RedirectToAction(nameof(UsersController.Profile), new { Username = this.User.Identity.Name });
        }

        private IActionResult RedirectToAll() => RedirectToAction(nameof(All));
    }
}

CameraBazaar.Web/Views/Cameras/Add.cshtml
@model AddCameraViewModel
@{
    ViewData["Title"] = "Add Camera";
}

<h2>@ViewData["Title"]</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Make"></label>
                <select asp-for="Make" asp-items="Html.GetEnumSelectList<CameraMakeType>()" class="form-control"></select>
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" min="0" step="1" max="100" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinShutterSpeed"></label>
                <input asp-for="MinShutterSpeed" min="1" step="1" max="30" class="form-control" />
                <span asp-validation-for="MinShutterSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxShutterSpeed"></label>
                <input asp-for="MaxShutterSpeed" min="2000" step="1" max="8000" class="form-control" />
                <span asp-validation-for="MaxShutterSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinISO"></label>
                <select asp-for="MinISO" asp-items="Html.GetEnumSelectList<MinISOType>()" class="form-control"></select>
                <span asp-validation-for="MinISO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxISO"></label>
                <input asp-for="MaxISO" min="200" step="100" max="409600" class="form-control" />
                <span asp-validation-for="MaxISO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsFullFrame"></label>
                @Html.RadioButtonFor(m => m.IsFullFrame, true) Yes
                @Html.RadioButtonFor(m => m.IsFullFrame, false) No
                <span asp-validation-for="IsFullFrame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoResolution"></label>
                <input asp-for="VideoResolution" class="form-control" />
                <span asp-validation-for="VideoResolution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LightMeterings"></label>
                <input type="checkbox" name="LightMeterings" value="@((int)LightMeteringType.Spot)" />Spot
                <input type="checkbox" name="LightMeterings" value="@((int)LightMeteringType.CenterWeighted)" />Center-Weighted
                <input type="checkbox" name="LightMeterings" value="@((int)LightMeteringType.Evaluative)" />Evaluative
                <span asp-validation-for="LightMeterings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-default">Add Camera</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

CameraBazaar.Web/Views/Cameras/All.cshtml
@model IEnumerable<AllCamerasServiceModel>
@{
    ViewData["Title"] = "All Cameras";
}

<div class="row">
    <div class="col-md-4">
        <h2>@ViewData["Title"] <a class="btn btn-primary btn-lg" asp-area="" asp-controller="Cameras" asp-action="Add">Add Camera</a></h2>
    </div>
</div>
<hr />
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card-group">
                @foreach (var cam in Model)
                {
                    <div class="card col-md-4 thumbnail">

                        <img class="card-image-top img-fluid img-thumbnail"
                             src="@cam.ImageURL">
                        <div class="card-body">
                            <h4 class="card-title text-center">@($"{cam.Make} {cam.Model}")</h4>
                            <p class="card-text text-center"><strong>Price</strong> - cam.Price&dollar;</p>
                            <p class="card-text text-center">@Html.Stock(cam.Quantity)</p>
                        </div>

                        <div class="card-footer">
                            <a class="btn btn-primary btn-lg btn-group-justified" href="/Cameras/Details/@cam.Id">Details</a>
                        </div>

                    </div>
                }
            </div>
        </div>
    </div>
</div>

CameraBazaar.Web/Views/Cameras/Delete.cshtml
@model int
@{
    ViewData["Title"] = "Delete";
}

<h2>Are you shure you want to delete this camera</h2>
<a href="/Users/Profile?Username=@Context.User.Identity.Name" class="btn btn-default">Back</a>
<a href="/Cameras/Destroy/@Model" class="btn btn-danger">Confirm Delete</a>

CameraBazaar.Web/Views/Cameras/Details.cshtml
@model CameraDetailsServiceModel
@{
    ViewData["Title"] = "Details";
}

<h3>@Model.Model @Model.Make - $@Model.Price – @Html.Stock(Model.Quantity)</h3>
<h3><a href="/Users/Profile?Username=@Model.Username">@Model.Username</a></h3>
<br />
<img class="card-image-top img-fluid img-thumbnail" src="@Model.ImageURL" width="20%" height="20%"/>
<br />
@Html.Partial("_CameraDetails", Model)
<a href="/Cameras/All" class="btn btn-success btn-lg">Back To All Cameras</a>

CameraBazaar.Web/Views/Cameras/Edit.cshtml
@model EditCameraServiceModel
@{
    ViewData["Title"] = "Edit Camera";
}

<h2>@ViewData["Title"]</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Make"></label>
                <select asp-for="Make" asp-items="Html.GetEnumSelectList<CameraMakeType>()" class="form-control"></select>
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" min="0" step="1" max="100" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinShutterSpeed"></label>
                <input asp-for="MinShutterSpeed" min="1" step="1" max="30" class="form-control" />
                <span asp-validation-for="MinShutterSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxShutterSpeed"></label>
                <input asp-for="MaxShutterSpeed" min="2000" step="1" max="8000" class="form-control" />
                <span asp-validation-for="MaxShutterSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinISO"></label>
                <select asp-for="MinISO" asp-items="Html.GetEnumSelectList<MinISOType>()" class="form-control"></select>
                <span asp-validation-for="MinISO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxISO"></label>
                <input asp-for="MaxISO" min="200" step="100" max="409600" class="form-control" />
                <span asp-validation-for="MaxISO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsFullFrame"></label>
                @Html.RadioButtonFor(m => m.IsFullFrame, true) Yes
                @Html.RadioButtonFor(m => m.IsFullFrame, false) No
                <span asp-validation-for="IsFullFrame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoResolution"></label>
                <input asp-for="VideoResolution" class="form-control" />
                <span asp-validation-for="VideoResolution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LightMeterings"></label>
                <input type="checkbox" name="LightMeterings" value="@((int)LightMeteringType.Spot)" @(Model.LightMeterings.Contains(LightMeteringType.Spot) ? "checked" : string.Empty) />Spot
                       <input type="checkbox" name="LightMeterings" value="@((int)LightMeteringType.CenterWeighted)"  @(Model.LightMeterings.Contains(LightMeteringType.CenterWeighted) ? "checked" : string.Empty) />Center-Weighted
                <input type="checkbox" name="LightMeterings" value="@((int)LightMeteringType.Evaluative)" @(Model.LightMeterings.Contains(LightMeteringType.Evaluative) ? "checked" : string.Empty) />Evaluative
                <span asp-validation-for="LightMeterings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-default">Edit Camera</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}